#Application
spring.application.name=bibliotheque

#Datasource
spring.datasource.url=jdbc:postgresql://localhost:5432/bibliotheque_db
spring.datasource.username=postgres
spring.datasource.password=motdepasse

#JPA
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

#Server
server.port=8080
